### ISSUE TITLE
Faulty line 431494 in 'fasttext_english_twitter_100d.vec'

### ISSUE THREAD

**Issue by cesarrodrig** [pedrada88/crossembeddings-twitter#2]
There is an extra `.` separated by a space in row 431495 of `fasttext_english_twitter_100d.vec`:

`
. . 0.074009 -0.29639 0.040341 0.24868 0.032798 0.3054 0.12288 -0.14644 -0.10465 -0.23429 0.099402 -0.00072593 0.041807 -0.20819 0.25566 -0.28076 -0.18242 0.095158 -0.57206 -0.10816 0.19682 0.17734 0.1421 -0.1863 -0.085888 -0.10674 0.24056 -0.10934 -0.059473 -0.082295 0.11698 0.38661 0.0084929 0.088395 0.081486 -0.16957 -0.080068 -0.2847 0.21914 -0.19544 -0.30694 0.27049 0.20239 0.24941 0.011246 -0.069467 0.081932 0.20728 -0.42698 0.51448 0.25806 -0.028937 -0.16024 -0.028767 0.30661 0.42475 0.088804 -0.30582 0.60831 0.43868 -0.21845 -0.049646 -0.082173 -0.30089 0.28805 0.099712 -0.145 0.3094 -0.22291 0.33128 -0.63606 0.15165 0.26595 0.42222 0.23574 0.2195 0.046564 0.033946 -0.15987 0.24569 0.17362 -0.11124 -0.37077 0.3057 0.26944 0.24637 0.24339 0.099499 -0.12623 -0.30971 0.056686 -0.28023 0.059675 0.11559 -0.034927 -0.2162 0.045346 -0.2391 -0.011809 -0.072241
`
Removing it fixes the issue. If you want, I can open a PR for this.

**Comment by pedrada88** [comment]
Thanks for catching this! It seems it was some kind of non-ASCII character which was not taken care of. We have now updated the vector file without this character.
